Repository roniemartinez/browsers, pull requests merged in 2025-05, with the labels that each got.

#180 🐛 Naively find browsers on unindexed OSX setup
  browsers/osx.py
  poetry.lock
  pyproject.toml
  tests/test_detect.py
Labels: fix

#183 Remove pyxdg module
  browsers/linux.py
  poetry.lock
  pyproject.toml
Labels: enhancement, dependencies

#189 🏁 Use ctypes to get application version
  .github/workflows/python.yml
  Makefile
  Taskfile.yml
  browsers/windows.py
  poetry.lock
  pyproject.toml
Labels: enhancement, dependencies

#190 ✨ Support Firefox-based browsers
  browsers/linux.py
  browsers/osx.py
  browsers/windows.py
  pyproject.toml
Labels: enhancement

#191 📚 Update documentation
  .gitignore
  .idea/dictionaries/project.xml
  README.md
  Taskfile.yml
  browsers/__init__.py
  pyproject.toml
Labels: documentation

#192 ✨ Support more browsers
  .idea/dictionaries/project.xml
  browsers/__init__.py
  browsers/linux.py
  browsers/osx.py
  pyproject.toml
Labels: enhancement

#197 🐧 Rewrite Linux desktop file search
  .idea/dictionaries/project.xml
  browsers/linux.py
  pyproject.toml
Labels: enhancement

#198 ✨ Support Flatpak
  .idea/dictionaries/project.xml
  browsers/linux.py
  pyproject.toml
Labels: enhancement
